### ISSUE TITLE
Adopt New UI

### ISSUE THREAD

**Issue by chrisdavidmiles** [newfold-labs/wp-plugin-hostgator#126]
Jira reference: e112fe71-3153-4ec4-81da-2fa84e817b27

**Comment by wpalani** [comment]
PR for this ticket: https://github.com/newfold-labs/wp-plugin-hostgator/pull/143

**Comment by wpalani** [comment]
We moved development branches to this https://github.com/newfold-labs/wp-plugin-hostgator/pull/180

**Comment by circlecube** [comment]
Complete with release of 2.0.0
