### ISSUE TITLE
Update the plugin update URL once repo is moved to the new GitHub org

### ISSUE THREAD

**Issue by wpscholar** [newfold-labs/wp-plugin-hostgator#6]
**Summarize the issue (briefly)**

Currently, the plugin update URL references the `bluehost` org. Once this repo is moved to the new org, we need to update the org name here: 
https://github.com/bluehost/wp-plugin-hostgator/blob/6fe078cc4a0824bebe300ba59031cfa583a730a8/bootstrap.php#L23

Additionally, there are a few references to the plugin update URL in the README file here: 
https://github.com/bluehost/wp-plugin-hostgator/blob/6fe078cc4a0824bebe300ba59031cfa583a730a8/README.md

**Comment by circlecube** [comment]
Fixed in #10
