### ISSUE TITLE
Change the PHPCS rule name

### ISSUE THREAD

**Issue by wpscholar** [newfold-labs/wp-plugin-hostgator#7]
**Summarize the issue (briefly)**

Update PHPCS rule name to be `HostGator` instead of `Bluehost` here: 
https://github.com/bluehost/wp-plugin-hostgator/blob/954e79c5d8c2aa9654d8bb8da0ba3118c1743cb0/phpcs.xml#L3

**Comment by circlecube** [comment]
Will revisit once the `bluehost/wp-php-standards` package is migrated and updated to include broader rule name.

**Comment by circlecube** [comment]
This is complete since 1.2.5
